### ISSUE TITLE
Account settings 

### ISSUE THREAD

**Issue by devCacti** [devCacti/Cooking#1]
**TODO:**
- [x] Create the page
- [x] Create a way of registering a new account
- [x] Create a way of logging in to an account

**After the above:**
- [x] A user can only create recipes if they have an account logged on
- [x] Manage to store the recipes for each user

**Comment by devCacti** [comment]
## Update:
It's supposed to work with the server and barely anything with the local storage, the local storage should only be used for user information (secure containers)
